disabled_rules:
- type_name
- force_cast
line_length: 300
excluded:
- Pods
- Share Beauty App/Views/DropDown/
- Share Beauty App/Views/WhiteLucentFeaturesView.swift
type_body_length:
- 200 # warning
- 700 # error
variable_name_max_length:
- 60 # warning
- 80 # error
variable_name_min_length:
- 1 # warning
- 0 # error
function_body_length:
- 100 # warning
- 200 # error